"""Added SysSupplierReq table

Revision ID: 0d4f2df89375
Revises: f92824e6c366
Create Date: 2025-10-01 19:49:19.882385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0d4f2df89375'
down_revision = 'f92824e6c366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_supplier_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('top_n', sqlite.JSON(), nullable=True),
    sa.Column('chosen_supplier_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_supplier_req_order_id'), 'sys_supplier_req', ['order_id'], unique=False)
    op.add_column('supplier', sa.Column('region', sa.String(), nullable=True))
    op.add_column('supplier', sa.Column('count_suppliers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'count_suppliers')
    op.drop_column('supplier', 'region')
    op.drop_index(op.f('ix_sys_supplier_req_order_id'), table_name='sys_supplier_req')
    op.drop_table('sys_supplier_req')
    # ### end Alembic commands ###
