"""Changed SysSupplierReq FKs from Order to Item and Product

Revision ID: 843002924ed8
Revises: 9e5e5df72ec2
Create Date: 2025-10-02 08:25:50.489543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843002924ed8'
down_revision = '9e5e5df72ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_supplier_req', schema=None) as batch_op:
        # Columns and indexes already added in partial migration, just add foreign keys and remove old column
        batch_op.create_foreign_key('fk_sys_supplier_req_item_id', 'item', ['item_id'], ['id'])
        batch_op.create_foreign_key('fk_sys_supplier_req_product_id', 'product', ['product_id'], ['id'])
        batch_op.drop_column('order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_supplier_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_sys_supplier_req_product_id'))
        batch_op.drop_index(batch_op.f('ix_sys_supplier_req_item_id'))
        batch_op.create_index('ix_sys_supplier_req_order_id', ['order_id'], unique=False)
        batch_op.drop_column('product_id')
        batch_op.drop_column('item_id')
    # ### end Alembic commands ###
