"""Moved count_suppliers from Supplier to Product

Revision ID: 9e5e5df72ec2
Revises: 0d4f2df89375
Create Date: 2025-10-02 08:12:41.161201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5e5df72ec2'
down_revision = '0d4f2df89375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('count_suppliers', sa.Integer(), nullable=True))
    op.drop_column('supplier', 'count_suppliers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('count_suppliers', sa.INTEGER(), nullable=True))
    op.drop_column('product', 'count_suppliers')
    # ### end Alembic commands ###
