"""Made item_id nullable in SysSupplierReq

Revision ID: ed0631795afb
Revises: 843002924ed8
Create Date: 2025-10-02 09:12:44.832016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0631795afb'
down_revision = '843002924ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_supplier_req', schema=None) as batch_op:
        batch_op.alter_column('item_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_supplier_req', schema=None) as batch_op:
        batch_op.alter_column('item_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
